baseurl: "/"

lang: en

title: Safa Safari

tagline: صفا صفری 

description: >- 
  Safa Safari, reverse engineer, network man, programmer

url: "https://Safa.re"

github:
  username: SafaSafari

twitter:
  username: SafaSafari3

social:
  name: Safa Safari
  email: SafaSafari.ss@gmail.com             
  links:
    - https://twitter.com/SafaSafari3      
    - https://github.com/SafaSafari       
    - https://www.linkedin.com/in/SafaSafari

theme: jekyll-theme-chirpy

avatar: ./safa.jpg

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true 
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs 
    values:
      layout: page
      permalink: /:title/

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json